[package]
name = "libadcs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["security-identifier", "ldap3-disco"]

[dependencies]
security-identifier = { path = "security-identifier" }
ldap3-disco = { path = "ldap3-disco" }
