[package]
name = "libdcerpc"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
hex.workspace = true
libdcerpc-sys = { path = "../libdcerpc-sys" }
bitflags = "2.0.0"
byteorder = "1.4.3"