<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
  targetNamespace="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xcep="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl">
  <wsdl:types>
    <xs:schema targetNamespace="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy">
      <xs:import namespace="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy" schemaLocation="xcep.xsd" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IPolicy_GetPolicies_InputMessage">
    <wsdl:part name="request" element="xcep:GetPolicies"/>
  </wsdl:message>
  <wsdl:message name="IPolicy_GetPolicies_OutputMessage">
    <wsdl:part name="response" element="xcep:GetPoliciesResponse"/>
  </wsdl:message>
  <wsdl:portType name="IPolicy">
    <wsdl:operation name="GetPolicies">
      <wsdl:input wsaw:Action="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy/IPolicy/GetPolicies" message="xcep:IPolicy_GetPolicies_InputMessage"/>
      <wsdl:output wsaw:Action="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy/IPolicy/GetPoliciesResponse" message="xcep:IPolicy_GetPolicies_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
 </wsdl:definitions>